# Generated by Django 5.1.5 on 2025-08-08 12:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=255, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('browser_name', models.CharField(blank=True, max_length=100, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=100, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('application_count', models.IntegerField(default=0)),
                ('last_application_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='Anonymous', max_length=255)),
                ('email', models.EmailField(default='not_provided@example.com', max_length=254)),
                ('phone', models.CharField(default='000-000-0000', max_length=20)),
                ('address', models.CharField(default='Not provided', max_length=255)),
                ('employment_status', models.CharField(default='Unemployed', max_length=20)),
                ('occupation', models.CharField(default='Not specified', max_length=100)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('repayment_duration', models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('24 months', '24 months')], default='12 months', max_length=20)),
                ('purpose', models.TextField(default='No purpose specified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('incognito', models.BooleanField(blank=True, null=True)),
                ('bot_detected', models.BooleanField(blank=True, null=True)),
                ('ip_blocklisted', models.BooleanField(blank=True, null=True)),
                ('tor_detected', models.BooleanField(blank=True, null=True)),
                ('vpn_detected', models.BooleanField(blank=True, null=True)),
                ('proxy_detected', models.BooleanField(blank=True, null=True)),
                ('tampering_detected', models.BooleanField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('fraud_patterns', models.JSONField(blank=True, null=True)),
                ('risk_factors', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visitor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fraud_detection.visitorid')),
            ],
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('APPROVE', 'Approved'), ('REVIEW', 'Manual Review Required'), ('REJECT', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='fraud_detection.loanapplication')),
                ('visitor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fraud_detection.visitorid')),
            ],
        ),
    ]
