# Generated by Django 5.1.5 on 2025-02-07 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='device_fingerprint',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='user',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='address',
            field=models.CharField(default='Not provided', max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(default='Unemployed', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='occupation',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='repayment_duration',
            field=models.CharField(choices=[('3 months', '3 months'), ('6 months', '6 months'), ('12 months', '12 months'), ('24 months', '24 months')], default='12 months', max_length=20),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='browser_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='amount_requested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='purpose',
            field=models.TextField(default='No purpose specified'),
        ),
        migrations.AlterField(
            model_name='visitorid',
            name='device_fingerprint',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
