# Generated by Django 5.1.5 on 2025-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_remove_loanapplication_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='browser_info',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='device_fingerprint',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='browser_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='continent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='incognito',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='subdivisions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
