# Generated by Django 5.1.5 on 2025-02-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_remove_loanapplication_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorid',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='device',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='incognito',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='subdivisions',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='timezone',
        ),
        migrations.AddField(
            model_name='visitorid',
            name='browser_engine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
