# Generated by Django 5.1.5 on 2025-02-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0003_fraudalert_metadata_loanapplication_fraud_patterns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
