# Generated by Django 5.1.5 on 2025-02-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0004_remove_visitorid_city_remove_visitorid_continent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorid',
            old_name='device_model',
            new_name='device',
        ),
        migrations.RemoveField(
            model_name='visitorid',
            name='device_type',
        ),
    ]
