# Generated by Django 5.1.5 on 2025-02-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0004_fraudalert_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
