# Generated by Django 5.1.5 on 2025-02-08 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0005_rename_device_model_visitorid_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorid',
            name='browser_engine',
        ),
    ]
