# Generated by Django 5.1.5 on 2025-02-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0005_alter_loanapplication_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='risk_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
