# Generated by Django 5.1.5 on 2025-02-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0007_loanapplication_public_ip_visitorid_public_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorid',
            name='incognito',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
