# Generated by Django 5.1.5 on 2025-02-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0007_alter_fraudalert_risk_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fraudalert',
            old_name='risk_level',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('fraud_detected', 'Fraud Detected')], default='pending', max_length=20),
        ),
    ]
