# Generated by Django 5.1.5 on 2025-02-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0008_visitorid_incognito'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='incognito',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
