# Generated by Django 5.1.5 on 2025-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0008_rename_risk_level_fraudalert_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudalert',
            name='status',
            field=models.CharField(choices=[('APPROVE', 'Approved'), ('REVIEW', 'Manual Review Required'), ('REJECT', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20),
        ),
    ]
