# Generated by Django 5.1.5 on 2025-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0009_loanapplication_incognito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='incognito',
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('APPROVE', 'Approved'), ('REVIEW', 'Manual Review Required'), ('REJECT', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='bot_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='ip_blocklisted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='proxy_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='tampering_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='tor_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitorid',
            name='vpn_detected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
